name: search
mode: builtin
activated_tools: null
config:
  summary_token_limit: 10_000
  search_engine: google  # google | jina | baidu | duckduckgo
  search_params: {"gl": "cn", "hl": "zh-cn"}  # search params for google & jina
  search_banned_sites: []
  JINA_API_KEY: ${oc.env:JINA_API_KEY}
config_llm:
  model_provider:
    type: ${oc.env:UTU_LLM_TYPE}
    model: ${oc.env:UTU_LLM_MODEL}
    api_key: ${oc.env:UTU_LLM_API_KEY}
    base_url: ${oc.env:UTU_LLM_BASE_URL}
